
using UnityEngine;
using UnityEngine.Tilemaps;


public class MapManager : MonoBehaviour
{
    public const int MAP_SIZE = 64;

    public class MapData{
        public TileBase texture;
        public tileTypes type;

        public bool can_walk = true;
        public bool can_build = true;
        public bool can_plant = true;

        public float fertility = 1.0f;
        public float humidity = 0.0f;
        public float light = 1.0f;

        public float walk_speed = 1.0f;
    }
    
    public Tilemap landTilemap;
    public Tilemap buildingTilemap;

    public enum tileTypes{
        grass,path,water,tree,total
    }
    
    public TileBase[] tiles = new TileBase[(int)tileTypes.total];

    public MapData[,] mapDatas = new MapData[MAP_SIZE, MAP_SIZE];

    //-------------generated by Copilot-----------------
    public void GenerateMapData(){
        for (int x = 0; x < MAP_SIZE; x++){
            for (int y = 0; y < MAP_SIZE; y++){
                mapDatas[x, y] = new MapData();
                mapDatas[x, y].type = tileTypes.grass;
                mapDatas[x, y].texture = tiles[(int)tileTypes.grass];
            }
        }
    }
    //-------------generated by Copilot----------------- 
    public void GenerateMapTiles(){
        for (int x = 0; x < MAP_SIZE; x++){
            for (int y = 0; y < MAP_SIZE; y++){
                landTilemap.SetTile(new Vector3Int(x, y, 0), mapDatas[x, y].texture);
            }
        }
    }

    public void Start(){
        GenerateMapData();
        GenerateMapTiles();
    }

}
